# Generated by Django 3.2a1 on 2021-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_path', models.CharField(max_length=200)),
                ('hash_name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('upload_count', models.IntegerField()),
            ],
        ),
    ]
