# Generated by Django 3.2a1 on 2021-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager_s3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
